version: "3"

services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=students_village